# Generated by Django 5.1.4 on 2026-05-25 04:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Код')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('discount_percent', models.PositiveSmallIntegerField(default=10, verbose_name='Скидка, %')),
                ('max_uses', models.PositiveIntegerField(default=100, verbose_name='Максимум использований')),
                ('uses', models.PositiveIntegerField(default=0, verbose_name='Использовано')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Действует с')),
                ('valid_to', models.DateTimeField(verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('minute', 'Поминутно'), ('hour', 'Почасово'), ('day', 'Посуточно')], default='minute', max_length=10, verbose_name='Тарификация')),
                ('status', models.CharField(choices=[('reserved', 'Забронирован'), ('active', 'В аренде'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='reserved', max_length=15, verbose_name='Статус')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Начало аренды')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Окончание аренды')),
                ('planned_end', models.DateTimeField(blank=True, null=True, verbose_name='Планируемое окончание')),
                ('start_address', models.CharField(blank=True, max_length=200, verbose_name='Адрес начала')),
                ('end_address', models.CharField(blank=True, max_length=200, verbose_name='Адрес окончания')),
                ('start_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Стартовая широта')),
                ('start_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Стартовая долгота')),
                ('end_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Конечная широта')),
                ('end_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Конечная долгота')),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Пробег, км')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость, ₽')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидка, ₽')),
                ('final_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итого к оплате, ₽')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('promo_code', models.CharField(blank=True, max_length=30, verbose_name='Промокод')),
                ('user_rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка поездки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='cars.car', verbose_name='Автомобиль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('topup', 'Пополнение'), ('rental', 'Оплата аренды'), ('bonus', 'Бонус'), ('fine', 'Штраф')], max_length=10, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма, ₽')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='rentals.rental')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-created_at',),
            },
        ),
    ]
