# Generated by Django 5.1.4 on 2026-05-25 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
                ('number_plate', models.CharField(max_length=15, unique=True, verbose_name='Гос. номер')),
                ('vin', models.CharField(blank=True, max_length=17, verbose_name='VIN')),
                ('car_class', models.CharField(choices=[('economy', 'Эконом'), ('comfort', 'Комфорт'), ('business', 'Бизнес'), ('suv', 'Кроссовер'), ('electro', 'Электрокар'), ('premium', 'Премиум')], default='economy', max_length=20, verbose_name='Класс')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('electric', 'Электро'), ('hybrid', 'Гибрид')], default='petrol', max_length=20, verbose_name='Топливо')),
                ('transmission', models.CharField(choices=[('auto', 'Автомат'), ('manual', 'Механика'), ('robot', 'Робот'), ('variator', 'Вариатор')], default='auto', max_length=20, verbose_name='Коробка')),
                ('seats', models.PositiveSmallIntegerField(default=5, verbose_name='Мест')),
                ('engine_volume', models.DecimalField(decimal_places=1, default=1.6, max_digits=3, verbose_name='Объём двигателя, л')),
                ('power_hp', models.PositiveIntegerField(default=100, verbose_name='Мощность, л.с.')),
                ('fuel_level', models.PositiveSmallIntegerField(default=100, verbose_name='Уровень топлива/заряда, %')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='Пробег, км')),
                ('has_child_seat', models.BooleanField(default=False, verbose_name='Детское кресло')),
                ('has_winter_tires', models.BooleanField(default=True, verbose_name='Зимняя резина')),
                ('status', models.CharField(choices=[('available', 'Свободен'), ('reserved', 'Забронирован'), ('rented', 'В аренде'), ('service', 'На обслуживании'), ('repair', 'В ремонте')], default='available', max_length=20, verbose_name='Статус')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Главное фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Рейтинг')),
                ('rentals_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во аренд')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ('brand', 'model'),
            },
        ),
        migrations.CreateModel(
            name='ParkingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('capacity', models.PositiveIntegerField(default=10, verbose_name='Вместимость')),
                ('has_charger', models.BooleanField(default=False, verbose_name='Зарядка для электрокаров')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Парковочная зона',
                'verbose_name_plural': 'Парковочные зоны',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название тарифа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price_per_minute', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена за минуту, ₽')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за час, ₽')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за сутки, ₽')),
                ('free_kilometers', models.PositiveIntegerField(default=200, verbose_name='Бесплатных км в сутки')),
                ('extra_km_price', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Цена за доп. км')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ('price_per_minute',),
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='Подпись')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
            options={
                'verbose_name': 'Фото авто',
                'verbose_name_plural': 'Фото авто',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='car',
            name='current_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.parkingzone', verbose_name='Парковочная зона'),
        ),
        migrations.AddField(
            model_name='car',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='cars.tariff', verbose_name='Тариф'),
        ),
        migrations.CreateModel(
            name='CarReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-created_at',),
                'unique_together': {('car', 'user')},
            },
        ),
    ]
