# Generated by Django 5.1.4 on 2026-05-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_filename',
            field=models.CharField(blank=True, help_text='Например: optima.jpg или Kia Sportage.jpg. Используется когда нет загруженного фото. Файл сначала залей в папку static/images/ через GitHub.', max_length=200, verbose_name='Имя файла в static/images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Главное фото (загрузить)'),
        ),
    ]
