# Generated by Django 5.1.4 on 2026-05-25 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_image_filename_alter_car_main_image'),
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_class',
            field=models.CharField(choices=[('economy', 'Эконом'), ('comfort', 'Комфорт'), ('business', 'Бизнес'), ('suv', 'Кроссовер'), ('electro', 'Электрокар'), ('premium', 'Премиум'), ('cabrio', 'Кабриолет'), ('van', 'Минивэн'), ('truck', 'Грузовой')], default='economy', max_length=20, verbose_name='Класс'),
        ),
        migrations.CreateModel(
            name='LocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('speed_kmh', models.PositiveSmallIntegerField(default=0, verbose_name='Скорость, км/ч')),
                ('fuel_level', models.PositiveSmallIntegerField(default=100, verbose_name='Топливо/заряд, %')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время снимка')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pings', to='cars.car')),
                ('rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pings', to='rentals.rental')),
            ],
            options={
                'verbose_name': 'GPS-снимок',
                'verbose_name_plural': 'GPS-снимки (трекинг)',
                'ordering': ('-recorded_at',),
                'indexes': [models.Index(fields=['car', '-recorded_at'], name='cars_locati_car_id_8fe59d_idx')],
            },
        ),
    ]
